version: "3.5"

networks:
  app-tier:
    driver: bridge

services:
  postgres: 
    image: postgres
    ports:
      - 5432:5432
    expose:
      - "5432"
    networks:
      - app-tier   
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql
    command: postgres -c listen_addresses='*'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm run migrate up; npm start'
    env_file: .env
    depends_on:
      - postgres
    networks:
      - app-tier   